name: Team awesome's approval workflow
on: pull_request_review
jobs:
  labelWhenApproved:
    runs-on: ubuntu-latest
    steps: 
      - name: Add a label to PR 
        uses: pullreminders/label-when-approved-action@master
        env: 
          APPROVALS: "1"
          GITHUB_TOKEN: ${{ secrets.TOKEN1 }}
          ADD_LABEL: "approved"
          REMOVE_LABEL: "awaiting%20review"
