name: Team awesome's approval workflow
on: 
  pull_request:
    branches:
      - master
jobs:
  labelWhenPRCreated:
    runs-on: ubuntu-latest
    steps: 
      - name: Add a label to PR 
        uses: abinoda/label-when-approved-action@1.0.5
        env: 
          APPROVALS: "0"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_LABEL: "awaiting%20review"
