name: Awaiting Review
on:
  pull_request:
    types: opened
jobs:
  labelWhenApproved:
    runs-on: ubuntu-latest
    steps: 
      - name: Label approved pull requests
        uses: abinoda/label-when-approved-action@1.0.5
        env: 
          APPROVALS: "0"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_LABEL: "awaiting%20review"

